
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sakshi aggarwal
 */
public class addemployee extends javax.swing.JInternalFrame implements myinterf5 {
     String imagename = "";
    String oldfilename;
     File myfile;
     String oldpic;

    /**
     * Creates new form Frame2
     */
    public addemployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel1.setText("ID NO. :");

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Full Name :");

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Gender :");

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Address :");

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Pin Code :");

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Date of Birth :");

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Mobile No. :");

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Email :");

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Priviledge :");

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Job Title :");

        jLabel11.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Password :");

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Date of Join :");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jRadioButton1.setText("Male");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jRadioButton2.setText("Female");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Manager", "Employee" }));

        jLabel13.setText("                                                                                   ");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel14.setText("Basic Salary :");

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2))
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField1)
                    .addComponent(jTextField4)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jPasswordField1)
                    .addComponent(jFormattedTextField2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton2.setText("Create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton5.setText("Search by ID");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton6.setText("Search by Name");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDNO.", "Name", "Address", "Mobile", "Email", "Date of Join", "Salary"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel15.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel15.setText("List of Employees");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      //jdbc:subprotocol:subname   //create button
         boolean give = valid();   //function call to valid() function
         if(give==true)
         {
           boolean flag=false;
 
        if(myfile!=null)
        {
        if(myfile.length()<300000)
        {
        imagename=new java.util.Date().getTime() + myfile.getName();
        int i;
        FileInputStream rd = null;
        FileOutputStream outs = null;
        try {
        rd = new FileInputStream(myfile);  //read from myfile
        outs = new FileOutputStream("projectimages\\"+imagename);//writing the new file in 'projectimages' folder, in the project
        while ((i = rd.read()) !=-1) {
        outs.write(i); //copying from pictures to libimages byte by byte
        }
        }
        catch (Exception e) 
        {
        JOptionPane.showMessageDialog(rootPane, "Error Ocurred :" + e.getMessage());
        } 
        flag=true;
        }
        else
        {
        flag=false;
        JOptionPane.showMessageDialog(rootPane, "Please Upload Photo of less than 250kb ");
        }
        }
        else
        {
        imagename="default.jpg";
        flag=true;
        } 
   if(flag)
   {
        try
        {
        Connection myconn = DriverManager.getConnection(myurl,dbuser,dpass);  //driver is activated,as no user is made so root is taken
        try
        {
        String q="insert into addemployee values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";   //insert query is implemented,addstudent is name of table
        PreparedStatement myst=myconn.prepareStatement(q);
        myst.setString(1, jTextField1.getText());  //id
        myst.setString(2, jTextField2.getText());   //fullname
        if(jRadioButton1.isSelected())             //gender
        {
        myst.setString(3, "Male");
        }
        else if(jRadioButton2.isSelected())
        {
        myst.setString(3, "Female");
        }
        myst.setString(4, jTextArea1.getText());  //address
        myst.setString(5, jFormattedTextField2.getText());  //pin code
        SimpleDateFormat myformat1 = new SimpleDateFormat("yyyy-MM-dd");
        String dob = myformat1.format(jDateChooser1.getDate());
        myst.setString(6, dob);  //date of birth
        myst.setString(7, jFormattedTextField1.getText());  //mobile no
        myst.setString(8, jTextField4.getText());  //email
        myst.setString(9, jComboBox1.getSelectedItem().toString());  //priviledge
        myst.setString(10, jTextField5.getText());  //job title
        SimpleDateFormat myformat2 = new SimpleDateFormat("yyyy-MM-dd");
        String doj = myformat2.format(jDateChooser2.getDate());
        myst.setString(11, doj);  //date of join
        myst.setString(12, jPasswordField1.getText());  //password
        myst.setString(13, jTextField6.getText());  //basic salary
        myst.setString(14, imagename);  //image
        myst.executeUpdate();
        JOptionPane.showMessageDialog(rootPane,"Employee added Succesfully");
        clearfields();
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(rootPane,"Error Occured : " + e.getMessage());   
        }
        finally
        {
         myconn.close();   //to close the connection  
        }
        }
        catch(Exception e)
                {
                JOptionPane.showMessageDialog(rootPane,"Error Occured :" + e.getMessage());    
                }
   }
    }                  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //upload button for photo upload
      JFileChooser obj=new JFileChooser();
        obj.setFileFilter(new FileFilter() {  //dont show all files but image files only
        @Override
        public boolean accept(File f) {  //accept method has object of file class
        if(f.isDirectory()) 
            return true;
            String extension;
            extension=f.getName().substring(f.getName().lastIndexOf(".")+1);
            String allowed[]={"jpg","png","gif","jpeg"};
            for(String a:allowed)
            {
            if(a.equalsIgnoreCase(extension))
            {
            return true;
            }
            }
            return false;
            }
        @Override
        public String getDescription() {
        return "All Image Files";
        }
        });
            if(obj.showOpenDialog(rootPane)==JFileChooser.APPROVE_OPTION)
            {
            try
            { 
            myfile=obj.getSelectedFile();
            Image simg = ImageIO.read( new File(obj.getSelectedFile().getAbsolutePath())).getScaledInstance( jLabel13.getWidth(), jLabel13.getHeight(), Image.SCALE_AREA_AVERAGING);
            //anonymous object of ImageIO is created
            jLabel13.setIcon(new ImageIcon(simg));
            }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(rootPane, "Cannot read image");
            }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //update employee
         boolean give = valid();    //function call to valid() function
         if(give==true)
         {
             boolean flag=false;
 
        if(myfile!=null)
        {
        if(myfile.length()<300000)
        {
        imagename=new java.util.Date().getTime() + myfile.getName();
        int i;
        FileInputStream rd = null;
        FileOutputStream outs = null;
        try {
        rd = new FileInputStream(myfile);
        outs = new FileOutputStream("projectimages\\"+imagename);//writing the new file in 'projectimages' folder, in the project
        while ((i = rd.read()) !=-1) {
        outs.write(i); //copying from pictures to projectimages byte by byte
        }
        }
        catch (Exception e) 
        {
        JOptionPane.showMessageDialog(rootPane, "Error Ocurred :" + e.getMessage());
        } 
        flag=true;
        }
        else
        {
        flag=false;
        JOptionPane.showMessageDialog(rootPane, "Please Upload Photo of less than 250kb ");
        }
        }
        else
        {
        imagename=jLabel13.getIcon().toString();
        flag=true;
        } 
   if(flag)
   {
            try
            {
                String myurl = "jdbc:mysql://localhost/stockmgmt";
                Connection myconn = DriverManager.getConnection(myurl,"root","");  //driver is activated,as no user is made so root is taken
                try
                {
                 String q="update addemployee set name=? , gender=? , address=? , pcode=? , dob=? , phone = ? , email = ? , usertype = ? , jobtit = ?, doj = ? , password = ? ,bsal = ? ,image = ? where IDNO = ? ";   //update query is implemented,addemployee is name of table
        PreparedStatement myst=myconn.prepareStatement(q);
        myst.setString(1, jTextField2.getText());    //full name
        if(jRadioButton1.isSelected())
        {
        myst.setString(2, "Male");
        }
        else if(jRadioButton2.isSelected())
        {
        myst.setString(2, "Female");  //gender
        }
        myst.setString(3, jTextArea1.getText());  //address
        myst.setString(4, jFormattedTextField2.getText());  //pin code
        SimpleDateFormat myformat1 = new SimpleDateFormat("yyyy-MM-dd");
        String dob = myformat1.format(jDateChooser1.getDate());
        myst.setString(5, dob);  //date of birth
        myst.setString(6, jFormattedTextField1.getText());  //mobile no
        myst.setString(7, jTextField4.getText());  //email
        myst.setString(8, jComboBox1.getSelectedItem().toString());  //usertype
        myst.setString(9, jTextField5.getText());  //job title
        SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
        String doj = myformat.format(jDateChooser2.getDate());
        myst.setString(10, doj);  //date of join 
        myst.setString(11, jPasswordField1.getText());  //password
        myst.setString(12, jTextField6.getText());   //basic salary
        myst.setString(13,imagename);
        myst.setString(14, jTextField1.getText());
                    int count=myst.executeUpdate();
                    if(count>0)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Employee updated Succesfully");
                        clearfields();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane,"Employee not updated");
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error Occured :" + e.getMessage());
                }
                finally
                {
                    myconn.close();   //to close the connection
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error Occured : " + e.getMessage());
            }
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //for delete button
        //jdbc:subprotocol:subname
        String myurl = "jdbc:mysql://localhost/stockmgmt";
        try
        {
            Connection myconn = DriverManager.getConnection(myurl,"root","");  //driver is activated,as no user is made so root is taken
            try
            {
                int res = JOptionPane.showConfirmDialog(rootPane,"Are you sure to delete ?","Please Choose",JOptionPane.YES_OPTION,JOptionPane.WARNING_MESSAGE);
                if(res==JOptionPane.YES_OPTION)
                {
                    String q="delete from addemployee where IDNO = ? ";   //delete query is implemented,addemployee is name of table
                    PreparedStatement myst=myconn.prepareStatement(q);
                    myst.setString(1, jTextField1.getText());
                   
                    int count=myst.executeUpdate();
                    if(count>0)
                    {
                         File myfile = new File("projectimages\\" + oldpic);
                         myfile.delete();
                        JOptionPane.showMessageDialog(null,"Employee deleted Succesfully");
                        clearfields();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane,"Employee not deleted");
                        jButton4.setEnabled(false);
                    }
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error Occured : " + e.getMessage());
            }
            finally
            {
                myconn.close();   //to close the connection
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error Occured :" + e.getMessage()); 
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // search button
         String myurl = "jdbc:mysql://localhost/stockmgmt";
        try
        {
        Connection myconn = DriverManager.getConnection(myurl,"root","");  //driver is activated,as no user is made so root is taken
        try
        {
        String q="select * from addemployee where IDNO = ? ";   //insert query is implemented,addemployee is name of table
        PreparedStatement myst=myconn.prepareStatement(q);
        myst.setString(1,jTextField1.getText());  //IDNO
        ResultSet myres = myst.executeQuery();
        if(myres.next())
        {
            jTextField2.setText(myres.getString("name"));          //for showing details in text fields by cliking search button 
            if(myres.getString("gender").equalsIgnoreCase("male"))
            {
                jRadioButton1.setSelected(true);
            }
            else if(myres.getString("gender").equalsIgnoreCase("female"))
            {
                jRadioButton2.setSelected(true);
            }
            jTextArea1.setText(myres.getString("address"));
            jFormattedTextField2.setText(myres.getString("pcode"));
            jDateChooser1.setDate(myres.getDate("dob"));
            jFormattedTextField1.setText(myres.getString("phone"));
            jTextField4.setText(myres.getString("email"));
            jComboBox1.setSelectedItem("usertype");
            jTextField5.setText(myres.getString("jobtit"));
            jDateChooser2.setDate(myres.getDate("doj"));
            jPasswordField1.setText(myres.getString("password"));
            jTextField6.setText(myres.getString("bsal"));
            jLabel13.setIcon(new ImageIcon(ImageIO.read(new File("projectimages/"+myres.getString("image")))));
        }
        else
        {
        JOptionPane.showMessageDialog(rootPane,"Invalid Employee ID");
        clearfields();
        }
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(rootPane,"Error Occured :" + e.getMessage());   
        }
        finally
        {
         myconn.close();   //to close the connection  
        }
        }
        catch(Exception e)
                {
                JOptionPane.showMessageDialog(rootPane,"Error Occured : " + e.getMessage());    
                }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      // search by name
        String myurl = "jdbc:mysql://localhost/stockmgmt";
        try
        {
        Connection myconn = DriverManager.getConnection(myurl,"root","");  //driver is activated,as no user is made so root is taken
        try
        {
        String q="select * from addemployee where name like ? ";   //insert query is implemented,addemployee is name of table
        PreparedStatement myst=myconn.prepareStatement(q);
        myst.setString(1,jTextField2.getText());  //full name
        ResultSet myres = myst.executeQuery();
        DefaultTableModel mymodel = (DefaultTableModel)jTable1.getModel();
        if(myres.next())
        {
            mymodel.setRowCount(0);  //to delete previous displayed record to zero
            do                         //for table by clicking search button
            {
                String idno,na,addr,mob,mail,priv,jobtit,doj,sal;
                idno=myres.getString("IDNO");
                na=myres.getString("name");
                addr=myres.getString("address");
                mob=myres.getString("phone");
                mail=myres.getString("email");
                priv=myres.getString("usertype");
                jobtit=myres.getString("jobtit");
                doj=myres.getString("doj");
                sal=myres.getString("bsal");
                Object myrow[] = {idno,na,addr,mob,mail,priv,jobtit,doj,sal};
                mymodel.addRow(myrow);  //myrow is object[] type
            }
            while(myres.next());
        }
            else
            {
             JOptionPane.showMessageDialog(rootPane,"No Employee Found");
             clearfields();
             mymodel.setRowCount(0);
            }
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(rootPane,"Error Occured : " + e.getMessage());   
        }
        finally
        {
         myconn.close();   //to close the connection  
        }
        }
        catch(Exception e)
                {
                JOptionPane.showMessageDialog(rootPane,"Error Occured"  + e.getMessage());    
                }
      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // on search by name
        String myurl = "jdbc:mysql://localhost/stockmgmt";
        String idno = jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();  // IDNO
        try
        {
        Connection myconn = DriverManager.getConnection(myurl,"root","");  //driver is activated,as no user is made so root is taken
        try
        {
        String q="select * from addemployee where IDNO = ? ";   //insert query is implemented,addemployee is name of table
        PreparedStatement myst=myconn.prepareStatement(q);
        myst.setString(1,idno);  //idno
        ResultSet myres = myst.executeQuery();
       
        if(myres.next())
        {  
            jTextField1.setText(myres.getString("IDNO"));
            jTextField2.setText(myres.getString("name"));         // for showing details in text fields by cliking search button 
            if(myres.getString("gender").equalsIgnoreCase("male"))
            {
                jRadioButton1.setSelected(true);
            }
            else if(myres.getString("gender").equalsIgnoreCase("female"))
            {
                jRadioButton2.setSelected(true);
            }
            jTextArea1.setText(myres.getString("address"));
            jFormattedTextField2.setText(myres.getString("pcode"));
            jDateChooser1.setDate(myres.getDate("dob"));
            jFormattedTextField1.setText(myres.getString("phone"));
            jTextField4.setText(myres.getString("email"));
            jDateChooser2.setDate(myres.getDate("doj"));
            jComboBox1.setSelectedItem("usertype");
            jTextField5.setText(myres.getString("jobtit"));
            jPasswordField1.setText(myres.getString("password"));
            jTextField6.setText(myres.getString("bsal"));
            jLabel13.setIcon(new ImageIcon(ImageIO.read(new File("projectimages/"+myres.getString("image")))));
        }
        else
        {
        JOptionPane.showMessageDialog(rootPane,"Invalid Employee ID");
        clearfields();
        }
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(rootPane,"Error Occured : " + e.getMessage());   
        }
        finally
        {
         myconn.close();   //to close the connection  
        }
        }
        catch(Exception e)
                {
                JOptionPane.showMessageDialog(rootPane,"Error Occured :" + e.getMessage());    
                }
    }//GEN-LAST:event_jTable1MouseClicked
void clearfields()   //user defined function
        {
        jTextField1.setText(null);   //id
        jTextField2.setText(null);    //name
        jTextArea1.setText(null);
        jFormattedTextField2.setText(null);
        jFormattedTextField1.setText(null);  //mobile no
        jTextField4.setText(null);
        jTextField5.setText(null);
        jPasswordField1.setText(null);
        jTextField6.setText(null);
        jLabel13.setIcon(null);
        buttonGroup1.clearSelection();   //gender
}
boolean valid()     //user defined function for validations applied on save button and update button
        {
            if(jTextField1.getText().length()<0)
            {
                JOptionPane.showMessageDialog(rootPane,"Enter a valid Employee ID");
                return(false);
            }
            else if(jTextField2.getText().length()<2)
            {
                JOptionPane.showMessageDialog(rootPane,"Enter Full Name");
                return(false);
            }
            else if(jComboBox1.getSelectedIndex()==0)
            {
                JOptionPane.showMessageDialog(rootPane,"Enter Priviledge");
                return(false);
            }
            else if((jFormattedTextField1.getText().length()<10) || (jFormattedTextField1.getText().length()>10))
            {
                JOptionPane.showMessageDialog(rootPane,"Enter Mobile No");
                return(false);
            }
            else if(jRadioButton1.isSelected()==false && jRadioButton2.isSelected()==false)
            {
                 JOptionPane.showMessageDialog(rootPane,"Enter Gender");
                return(false);
            }
            else if(jTextField4.getText().length()<6 ||  jTextField4.getText().contains("@")==false)
            {
              JOptionPane.showMessageDialog(rootPane,"Enter correct e-mail");
                return(false);  
            }
            else if(jFormattedTextField2.getText().length()<6)
            {
              JOptionPane.showMessageDialog(rootPane,"Enter Pin Code");
                return(false);  
            }
            else if(jTextField5.getText().length()<4)
            {
              JOptionPane.showMessageDialog(rootPane,"Enter Job Title");
                return(false);  
            }
            else if(jPasswordField1.getText().length()<5)
            {
                JOptionPane.showMessageDialog(rootPane,"Enter Password");
                return(false);
            }
            else if(jTextField6.getText().length()<3)
            {
              JOptionPane.showMessageDialog(rootPane,"Enter Basic Salary");
                return(false);  
            }
            else
            {
                return(true);
            }
            
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
